# Generated by Django 5.2.13 on 2026-04-16 12:28

import amos.models
import amos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amos', '0002_add_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, help_text='Profile picture. JPEG, PNG, GIF, or WebP only; max 2 MB.', upload_to=amos.models._avatar_upload_to, validators=[amos.validators.validate_avatar]),
        ),
        migrations.AddField(
            model_name='profile',
            name='document',
            field=models.FileField(blank=True, help_text='A document to share. PDF or plain text only; max 5 MB.', upload_to=amos.models._document_upload_to, validators=[amos.validators.validate_document]),
        ),
    ]
